// src/app/api/tickets/route.ts - CORRECTED
import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/db/prisma';
import { getServerSession } from 'next-auth';
import { authOptions } from '../auth/[...nextauth]/route';

export async function PUT(request: NextRequest) {
    try {
        const session = await getServerSession(authOptions);
        if (!session) {
            return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
        }

        const { searchParams } = new URL(request.url);
        const id = searchParams.get('id');

        if (!id) {
            return NextResponse.json(
                { error: 'Ticket ID is required' },
                { status: 400 }
            );
        }

        const body = await request.json();
        const { status, resolution } = body;

        // Validate resolution is required when closing
        if (status === 'closed' && (!resolution || resolution.trim() === '')) {
            return NextResponse.json(
                { error: 'Resolution message is required to close a ticket' },
                { status: 400 }
            );
        }

        const updateData: any = {
            status,
            updatedAt: new Date(),
        };

        // Add resolution to update data
        if (status === 'closed') {
            updateData.resolution = resolution;
        }

        // Check if ID is UUID or numeric
        let whereCondition;
        const isUUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id);

        if (isUUID) {
            whereCondition = { uuid: id };
        } else {
            const numericId = parseInt(id);
            if (isNaN(numericId)) {
                return NextResponse.json({ error: 'Invalid ticket ID' }, { status: 400 });
            }
            whereCondition = { id: numericId };
        }

        const ticket = await prisma.ticket.update({
            where: whereCondition,
            data: updateData,
        });

        return NextResponse.json(ticket);
    } catch (error) {
        console.error('Error updating ticket:', error);
        return NextResponse.json(
            { error: 'Error updating ticket' },
            { status: 500 }
        );
    }
}

export async function POST(request: NextRequest) {
    try {
        const session = await getServerSession(authOptions);
        if (!session?.user?.email) {
            return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
        }

        const body = await request.json();
        const { subject, description, priority } = body; // Changed from 'title' to 'subject'

        // Validate required fields
        if (!subject?.trim()) {
            return NextResponse.json(
                { error: 'Subject is required' },
                { status: 400 }
            );
        }
        if (!description?.trim()) {
            return NextResponse.json(
                { error: 'Description is required' },
                { status: 400 }
            );
        }
        if (!priority) {
            return NextResponse.json(
                { error: 'Priority is required' },
                { status: 400 }
            );
        }

        const user = await prisma.user.findUnique({
            where: { email: session.user.email },
        });

        if (!user) {
            return NextResponse.json({ error: 'User not found' }, { status: 404 });
        }

        const ticket = await prisma.ticket.create({
            data: {
                subject: subject.trim(), // Changed from 'title' to 'subject'
                description: description.trim(),
                priority,
                userId: user.id,
                // UUID will be automatically generated by Prisma
            },
        });

        return NextResponse.json(ticket);

    } catch (error: any) {
        console.error('Error creating ticket:', error);

        // Handle specific errors
        let errorMessage = 'Error creating ticket';
        if (error.code === 'P2002') {
            errorMessage = 'Database constraint error (possibly duplicate UUID)';
        }

        return NextResponse.json(
            { error: errorMessage },
            { status: 500 }
        );
    }
}

// Add GET method to fetch all tickets for the current user
export async function GET(request: NextRequest) {
    try {
        const session = await getServerSession(authOptions);
        if (!session?.user?.email) {
            return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
        }

        const user = await prisma.user.findUnique({
            where: { email: session.user.email },
        });

        if (!user) {
            return NextResponse.json({ error: 'User not found' }, { status: 404 });
        }

        const tickets = await prisma.ticket.findMany({
            where: { userId: user.id },
            orderBy: { createdAt: 'desc' },
            select: {
                id: true,
                uuid: true,
                subject: true, // Changed from 'title' to 'subject'
                description: true,
                status: true,
                priority: true,
                createdAt: true,
                updatedAt: true,
            },
        });

        return NextResponse.json(tickets);
    } catch (error) {
        console.error('Error fetching tickets:', error);
        return NextResponse.json(
            { error: 'Error fetching tickets' },
            { status: 500 }
        );
    }
}
